version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx-ktl
    restart: always
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./docker/nginx/logs:/var/log/nginx
      - ./src/:/var/www/html
    networks:
      - nginx
      - db
    depends_on:
      - 'php'
    ports:
      - '9090:80'

  php:
    build: ./docker/php7.4
    container_name: php-ktl
    restart: always
    networks:
      - nginx
      - db
    depends_on:
      - 'postgres'
    volumes:
      - ./src/:/var/www/html
      - ./docker/php7.4/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  postgres:
    build: ./docker/postgres
    container_name: postgres-ktl
    restart: always
    networks:
      - db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/postgres/var/lib/postgres:/var/lib/postgres

networks:
  nginx:
  db:
